version: '3.8'

services:
  data-populator:
    build:
      context: ../..
      dockerfile: apps/data-populator/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
      - PINATA_JWT_KEY
      - PINATA_GATEWAY_KEY
      - IPFS_GATEWAY
      - PRIVATE_KEY
      - PRIVATE_KEY_DEV
      - ADDITIONAL_STAKE_ATOM=100000000000
      - ADDITIONAL_STAKE_TRIPLE=100000000000
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - SUPABASE_URL
      - SUPABASE_KEY
      - VITE_ALCHEMY_API_KEY
      - VITE_ORIGIN_URL=https://portal.intuition.systems
      - PRIVY_APP_ID
      - PRIVY_AUTH_URL
      - PRIVY_APP_SECRET
      - PRIVY_VERIFICATION_KEY
      - VITE_DEPLOY_ENV=development
